// Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.
import { access, accessPromise, accessSync } from "./_fs/_fs_access.ts";
import {
  appendFile,
  appendFilePromise,
  appendFileSync,
} from "./_fs/_fs_appendFile.js";
import { chmod, chmodPromise, chmodSync } from "./_fs/_fs_chmod.js";
import { chown, chownPromise, chownSync } from "./_fs/_fs_chown.js";
import { close, closeSync } from "./_fs/_fs_close.js";
import * as constants from "./_fs/_fs_constants.js";
import { copyFile, copyFilePromise, copyFileSync } from "./_fs/_fs_copy.js";
import Dir from "./_fs/_fs_dir.js";
import Dirent from "./_fs/_fs_dirent.js";
import { exists, existsSync } from "./_fs/_fs_exists.js";
import { fdatasync, fdatasyncSync } from "./_fs/_fs_fdatasync.js";
import { fstat, fstatSync } from "./_fs/_fs_fstat.js";
import { fsync, fsyncSync } from "./_fs/_fs_fsync.js";
import { ftruncate, ftruncateSync } from "./_fs/_fs_ftruncate.js";
import { futimes, futimesSync } from "./_fs/_fs_futimes.js";
import { link, linkPromise, linkSync } from "./_fs/_fs_link.js";
import { lstat, lstatPromise, lstatSync } from "./_fs/_fs_lstat.js";
import { mkdir, mkdirPromise, mkdirSync } from "./_fs/_fs_mkdir.js";
import { mkdtemp, mkdtempPromise, mkdtempSync } from "./_fs/_fs_mkdtemp.js";
import { open, openPromise, openSync } from "./_fs/_fs_open.js";
import { opendir, opendirPromise, opendirSync } from "./_fs/_fs_opendir.js";
import { read, readSync } from "./_fs/_fs_read.js";
import { readdir, readdirPromise, readdirSync } from "./_fs/_fs_readdir.js";
import { readFile, readFilePromise, readFileSync } from "./_fs/_fs_readFile.js";
import { readlink, readlinkPromise, readlinkSync } from "./_fs/_fs_readlink.js";
import { realpath, realpathPromise, realpathSync } from "./_fs/_fs_realpath.js";
import { rename, renamePromise, renameSync } from "./_fs/_fs_rename.js";
import { rmdir, rmdirPromise, rmdirSync } from "./_fs/_fs_rmdir.js";
import { rm, rmPromise, rmSync } from "./_fs/_fs_rm.js";
import { stat, statPromise, statSync } from "./_fs/_fs_stat.js";
import { symlink, symlinkPromise, symlinkSync } from "./_fs/_fs_symlink.js";
import { truncate, truncatePromise, truncateSync } from "./_fs/_fs_truncate.js";
import { unlink, unlinkPromise, unlinkSync } from "./_fs/_fs_unlink.js";
import { utimes, utimesPromise, utimesSync } from "./_fs/_fs_utimes.js";
import {
  unwatchFile,
  watch,
  watchFile,
  watchPromise,
} from "./_fs/_fs_watch.js";
// @deno-types="./_fs/_fs_write.d.js"
import { write, writeSync } from "./_fs/_fs_write.mjs";
// @deno-types="./_fs/_fs_writev.d.js"
import { writev, writevSync } from "./_fs/_fs_writev.mjs";
import {
  writeFile,
  writeFilePromise,
  writeFileSync,
} from "./_fs/_fs_writeFile.js";
import { Stats } from "./internal/fs/utils.mjs";
// @deno-types="./internal/fs/streams.d.ts"
import {
  createReadStream,
  createWriteStream,
  ReadStream,
  WriteStream,
} from "./internal/fs/streams.mjs";

const {
  F_OK,
  R_OK,
  W_OK,
  X_OK,
  O_RDONLY,
  O_WRONLY,
  O_RDWR,
  O_NOCTTY,
  O_TRUNC,
  O_APPEND,
  O_DIRECTORY,
  O_NOFOLLOW,
  O_SYNC,
  O_DSYNC,
  O_SYMLINK,
  O_NONBLOCK,
  O_CREAT,
  O_EXCL,
} = constants;

const promises = {
  access: accessPromise,
  copyFile: copyFilePromise,
  open: openPromise,
  opendir: opendirPromise,
  rename: renamePromise,
  truncate: truncatePromise,
  rm: rmPromise,
  rmdir: rmdirPromise,
  mkdir: mkdirPromise,
  readdir: readdirPromise,
  readlink: readlinkPromise,
  symlink: symlinkPromise,
  lstat: lstatPromise,
  stat: statPromise,
  link: linkPromise,
  unlink: unlinkPromise,
  chmod: chmodPromise,
  // lchmod: promisify(lchmod),
  // lchown: promisify(lchown),
  chown: chownPromise,
  utimes: utimesPromise,
  // lutimes = promisify(lutimes),
  realpath: realpathPromise,
  mkdtemp: mkdtempPromise,
  writeFile: writeFilePromise,
  appendFile: appendFilePromise,
  readFile: readFilePromise,
  watch: watchPromise,
};

export default {
  access,
  accessSync,
  appendFile,
  appendFileSync,
  chmod,
  chmodSync,
  chown,
  chownSync,
  close,
  closeSync,
  constants,
  copyFile,
  copyFileSync,
  createReadStream,
  createWriteStream,
  Dir,
  Dirent,
  exists,
  existsSync,
  F_OK,
  fdatasync,
  fdatasyncSync,
  fstat,
  fstatSync,
  fsync,
  fsyncSync,
  ftruncate,
  ftruncateSync,
  futimes,
  futimesSync,
  link,
  linkSync,
  lstat,
  lstatSync,
  mkdir,
  mkdirSync,
  mkdtemp,
  mkdtempSync,
  O_APPEND,
  O_CREAT,
  O_DIRECTORY,
  O_DSYNC,
  O_EXCL,
  O_NOCTTY,
  O_NOFOLLOW,
  O_NONBLOCK,
  O_RDONLY,
  O_RDWR,
  O_SYMLINK,
  O_SYNC,
  O_TRUNC,
  O_WRONLY,
  open,
  openSync,
  opendir,
  opendirSync,
  read,
  readSync,
  promises,
  R_OK,
  readdir,
  readdirSync,
  readFile,
  readFileSync,
  readlink,
  readlinkSync,
  ReadStream,
  realpath,
  realpathSync,
  rename,
  renameSync,
  rmdir,
  rmdirSync,
  rm,
  rmSync,
  stat,
  Stats,
  statSync,
  symlink,
  symlinkSync,
  truncate,
  truncateSync,
  unlink,
  unlinkSync,
  unwatchFile,
  utimes,
  utimesSync,
  W_OK,
  watch,
  watchFile,
  write,
  writeFile,
  writev,
  writevSync,
  writeFileSync,
  WriteStream,
  writeSync,
  X_OK,
};

export {
  access,
  accessSync,
  appendFile,
  appendFileSync,
  chmod,
  chmodSync,
  chown,
  chownSync,
  close,
  closeSync,
  constants,
  copyFile,
  copyFileSync,
  createReadStream,
  createWriteStream,
  Dir,
  Dirent,
  exists,
  existsSync,
  F_OK,
  fdatasync,
  fdatasyncSync,
  fstat,
  fstatSync,
  fsync,
  fsyncSync,
  ftruncate,
  ftruncateSync,
  futimes,
  futimesSync,
  link,
  linkSync,
  lstat,
  lstatSync,
  mkdir,
  mkdirSync,
  mkdtemp,
  mkdtempSync,
  O_APPEND,
  O_CREAT,
  O_DIRECTORY,
  O_DSYNC,
  O_EXCL,
  O_NOCTTY,
  O_NOFOLLOW,
  O_NONBLOCK,
  O_RDONLY,
  O_RDWR,
  O_SYMLINK,
  O_SYNC,
  O_TRUNC,
  O_WRONLY,
  open,
  opendir,
  opendirSync,
  openSync,
  promises,
  R_OK,
  read,
  readdir,
  readdirSync,
  readFile,
  readFileSync,
  readlink,
  readlinkSync,
  ReadStream,
  readSync,
  realpath,
  realpathSync,
  rename,
  renameSync,
  rm,
  rmdir,
  rmdirSync,
  rmSync,
  stat,
  Stats,
  statSync,
  symlink,
  symlinkSync,
  truncate,
  truncateSync,
  unlink,
  unlinkSync,
  unwatchFile,
  utimes,
  utimesSync,
  W_OK,
  watch,
  watchFile,
  write,
  writeFile,
  writeFileSync,
  WriteStream,
  writeSync,
  writev,
  writevSync,
  X_OK,
};
