[package]
name = "deno_std_wasm_varint"
repository = "https://github.com/denoland/deno_std"
authors = ["the Deno authors"]
license = "MIT"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3

[dependencies]
wasm-bindgen = "0.2.83"